# Dependencies
highlighter: pygments
markdown:    redcarpet
redcarpet:
  extensions: [
    'no_intra_emphasis',
    'fenced_code_blocks',
    'autolink',
    'strikethrough',
    'superscript',
    'with_toc_data',
    'tables',
    'hardwrap'
  ]


# Setup
title:       'CrimeWatch'
tagline:     'Documentation for CrimeWatch apps and projects.'
description: 'This site contains documentation for the watching of crimes.  ಠ_ಠ'
baseurl:     /
future:      true
paginate:    30
theme:       'theme-base-0d'


# Permalinks
permalink:   pretty


# Exclude non-site files
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
